apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-data
data:
  init.js: |
    db = db.getSiblingDB('springboot_mongo');
    db.createUser({
      user: 'springuser',
      pwd: 'springpassword',
      roles: [
        {
          role: 'readWrite',
          db: 'springboot_mongo'
        }
      ]
    });
    db.createCollection('products');