apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # echo -n 'your-root-password' | base64
  MONGO_INITDB_ROOT_PASSWORD: eW91ci1yb290LXBhc3N3b3Jk
  # echo -n 'your-root-username' | base64
  MONGO_INITDB_ROOT_USERNAME: eW91ci1yb290LXVzZXJuYW1l