apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  mongo.conf: |
    storage:
      dbPath: /data/db
    systemLog:
      destination: file
      path: /data/log/mongodb.log
      logAppend: true
    net:
      bindIp: 0.0.0.0
      port: 27017