apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: {{ .Release.Name }}-payment-service-app
  ports:
      - protocol: TCP
        port: 2026
        targetPort: 2026
  type: ClusterIP