spring:
  config:
    import:
      optional:/home/as/Downloads/e-commerce-project-master/order-service/.env[.properties],optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
server:
  port: 2022

springdoc:
  swagger-ui:
    disable-swagger-default-url : true
    path: "/order-service/swagger-ui"

