apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: {{ .Release.Name }}-product-catalog-service-app
  ports:
      - protocol: TCP
        port: 2025
        targetPort: 2025
  type: ClusterIP