spring:
  config:
    import:
      optional:/home/as/Downloads/e-commerce-project-master/cart-service/.env[.properties],optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}


springdoc:
  swagger-ui:
    disable-swagger-default-url : true
    path: "/cart-service/swagger-ui"

