apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: order-service-app
  template:
    metadata:
      labels:
        app: order-service-app
    spec:
      containers:
        - name: order-service-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 2022
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ include "spring-app.postgresqlURL" . | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                   name: postgres-secret
                   key: POSTGRES_PASSWORD
            - name: SPRING_PROFILES_ACTIVE
              value: dep
            - name: KAFKA_URL
              value: kafka-service:9092
            - name: AXON_URL
              value: axonserver-grpc:8124
            - name: KEYCLOAK_URL
              value: "http://172.22.0.204:8080/auth/realms/e-commerce"