spring:
  config:
    import:
      optional:/home/as/Downloads/e-commerce-project-master/product-catalog-service/.env[.properties],optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
springdoc:
  swagger-ui:
    disable-swagger-default-url : true
    path: "/product-service/swagger-ui"
